Add limitations
tastyigniter/ti-ext-coupons pull request #1
Opened 2020-10-17 08:30 UTC by ryanmitchell

@sampoyigi Can you check this over, it should be good to go now.

2020-10-17 12:52 UTC, sampoyigi requested changes

2020-10-17 12:52 UTC, sampoyigi commented on database/migrations/2020_10_15_000300_create_cart_restriction.php
> +            $table->boolean('is_limited')->default(false);
From the database schema, it's hard to tell what value this column holds. Maybe `is_limited_to_cart_item` or `applies_to_cart_item`? Sorry about the back and forth ;)

2020-10-17 14:23 UTC, ryanmitchell commented
What about something like 

has_limited_scope

?

> On 17 Oct 2020, at 13:52, Sam Poyigi <notifications@github.com> wrote:
> 
> ﻿
> @sampoyigi requested changes on this pull request.
> 
> In database/migrations/2020_10_15_000300_create_cart_restriction.php:
> 
> > @@ -0,0 +1,17 @@
> +<?php
> +
> +namespace Igniter\Coupons\Database\Migrations;
> +
> +use Illuminate\Database\Migrations\Migration;
> +use Illuminate\Database\Schema\Blueprint;
> +use Illuminate\Support\Facades\Schema;
> +
> +class CreateCartRestriction extends Migration
> +{
> +    public function up()
> +    {
> +        Schema::table('igniter_coupons', function (Blueprint $table) {
> +            $table->boolean('is_limited')->default(false);
> From the database schema, it's hard to tell what value this column holds. Maybe is_limited_to_cart_item or applies_to_cart_item? Sorry about the back and forth ;)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-17 14:49 UTC, sampoyigi commented
Still not descriptive enough.

2020-10-17 15:02 UTC, ryanmitchell commented
Trying to avoid including item in the string as I’m conscious it may not always be limiting items - might be quantities or something else. It’s a general ‘is this scope of this coupon limited in any way’

2020-10-18 12:32 UTC, sampoyigi commented
Yea but we should be keeping things extremely simple and Coupons are already limited by different fields in the db, adding another one without being specific creates confusion. We can always add a new field if needed.

2020-10-18 12:42 UTC, ryanmitchell commented
Np. I’ve updated it now to is_limited_to_cart_item

> On 18 Oct 2020, at 13:33, Sam Poyigi <notifications@github.com> wrote:
> 
> 
> Yea but we should be keeping things extremely simple and Coupons are already limited by different fields in the db, adding another one without being specific creates confusion. We can always add a new field if needed.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/tastyigniter/ti-ext-coupons/pull/1#issuecomment-711161282>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAMVO3ALC2LNWCJKSCPWOLSLLN77ANCNFSM4SUGXWKA>.
>

2020-10-22 00:56 UTC, sampoyigi requested changes

2020-10-22 00:56 UTC, sampoyigi commented on cartconditions/Coupon.php
> +        if (!$couponModel OR !$couponModel->is_limited_to_cart_item)
This should probably change to `if (!$couponModel OR $couponModel->is_limited_to_cart_item)`

2020-10-29 05:16 UTC, merged