Fix location issue
tastyigniter/ti-ext-coupons pull request #10
Opened 2021-01-13 21:12 UTC by BreakSecurity

2021-01-14 15:48 UTC, sampoyigi requested changes

2021-01-14 15:48 UTC, sampoyigi commented on requests/Coupon.php
> +            ['locations', 'admin::lang.column_location', 'required'],
For the sake of consistency, the `locations` rule should come before `locations.*`

2021-01-19 12:27 UTC, sampoyigi approved these changes

2021-01-19 12:28 UTC, merged

2021-01-19 12:28 UTC, sampoyigi commented
Thank you!

2021-02-04 01:05 UTC, sampoyigi commented
Ok reverting this as we want users to be able to create non-locationable coupons.

2021-02-04 01:10 UTC, BreakSecurity commented
I'm not sure user will see the coupons with no location attached, but I agre

2021-02-04 01:22 UTC, sampoyigi commented
Yup, just fixed that here tastyigniter/TastyIgniter@13f7e82a9ed801d20765af84b2dd999f4291a926 and ffc18e116aae37c35517081867adb8684bdf4528