Use order time when instead current time
tastyigniter/ti-ext-coupons pull request #14
Opened 2021-02-01 23:25 UTC by Zelig880

2021-02-02 08:31 UTC, ryanmitchell commented
Looks good to me once you tidy up the StyleCI.
@sampoyigi any objections to this commit being merged?

2021-02-02 21:59 UTC, Zelig880 commented
@ryanmitchell @sampoyigi All fixed for you

2021-02-02 23:02 UTC, sampoyigi requested changes

2021-02-02 23:02 UTC, sampoyigi commented on models/Coupons_model.php
> +    public function isExpired($orderDateTime)
For backward compatibility, make the `$orderDateTime` optional with a default value of null so we can use still use the current time when nothing is passed.

Something like this 

```
public function isExpired($orderDateTime = null) {
   if (is_null($orderDateTime))
      $orderDateTime = Carbon::now();
   ....
}
```

2021-02-03 18:24 UTC, Zelig880 commented
All changed and tested.

2021-02-04 00:04 UTC, sampoyigi approved these changes

2021-02-04 00:05 UTC, merged